### ISSUE TITLE
Control audio

### ISSUE THREAD

**Issue by bendschs** [carceneaux/alfred-youtube-music-control#1]
how would i control the volume of the player?

testet something like this (but it's not working yet):

```
on alfred_script(q)
tell application "Google Chrome"
  set allWins to every window
  set allTabs to {}
    repeat with currWin in allWins
      set allTabs to allTabs & every tab of currWin
    end repeat
    repeat with currTab in allTabs
      try
        if (title of currTab) contains "Youtube Music" then set musicTab to currTab
      end try
    end repeat
  tell musicTab to execute javascript "(document.querySelector('[aria-label=\"Decrease volume\"]')).click();"
end tell
end alfred_script
```

**Comment by carceneaux** [comment]
Current code is mostly executing mouse clicks using javascript. In comparison, what you're looking for requires a setting change vs a click.

I just released a new version of the workflow with this capability. 😄  Enjoy!

https://github.com/carceneaux/alfred-youtube-music-control/releases/latest

The below screenshot demonstrates setting the volume to 80%:

![](https://i.imgur.com/SOOkBN7.jpg)
