### ISSUE TITLE
[Solved] Fix to Previous & Next no long working

### ISSUE THREAD

**Issue by johnathanz** [carceneaux/alfred-youtube-music-control#6]
Recently the Previous & Next functions (shortkey and ym..next and ym..previous) no longer worked. As Google recently changed the `aria-label` for Previous and Next buttons on the web player.

Make script changes to Previous and Next:
![2023-03-07 at 06 55 04](https://user-images.githubusercontent.com/1593039/223216608-2f95ccc5-cde6-4063-9842-ef6ab12d5227.png)

to:
![2023-03-07 at 06 52 32](https://user-images.githubusercontent.com/1593039/223216411-0e408f80-c017-420a-a7a5-dca94160248c.png)

Thanks @carceneaux for creating this plugin. It's fantastic! 😸

**Comment by johnathanz** [comment]
YT music rolled out more changes. This time, `aria-label=Next` is no longer a unique search criteria, it'll find multiple "next" buttons, including the ones that horizontally scroll the albums on Home or Library.

Replace the `tell musicTab to execute....` line in the script files with:

**Next Button:**
```
tell musicTab to execute javascript "(document.querySelector('[class=\"next-button style-scope ytmusic-player-bar\"][aria-label=\"Next\"]')).click();"
```

**Previous Button**
```
tell musicTab to execute javascript "( document.querySelector('[class=\"previous-button style-scope ytmusic-player-bar\"][aria-label=\"Previous\"]') ).click();"
```

**Comment by carceneaux** [comment]
Glad you like it! 😊

The latest release ([1.4.2](https://github.com/carceneaux/alfred-youtube-music-control/releases/tag/1.4.2)) incorporates these updates.
